# Generated by Django 5.1.2 on 2024-10-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='founded',
            field=models.DateField(),
        ),
    ]
