# Generated by Django 5.1.2 on 2024-10-29 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premier_django', '0002_alter_club_founded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='adress',
            new_name='address',
        ),
    ]
