# Generated by Django 5.1.2 on 2024-11-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premier_django', '0004_alter_standings_goal_difference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_stats',
            old_name='player_name',
            new_name='player_name_id',
        ),
    ]
