# Generated by Django 5.1.2 on 2024-11-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premier_django', '0005_rename_player_name_player_stats_player_name_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_stats',
            old_name='player_name_id',
            new_name='player_name',
        ),
    ]
