# Generated by Django 5.1.2 on 2024-11-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier_django', '0006_rename_player_name_id_player_stats_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='standings',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
    ]
