# Generated by Django 5.1.2 on 2024-11-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('Time_started', models.AutoField(primary_key=True, serialize=False)),
                ('Money_Used', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('Operation_Type', models.CharField(max_length=255)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Phone_Number', models.CharField(max_length=115)),
                ('Documents', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Terms_Of_Use', models.CharField(max_length=255)),
                ('Hashed_Password', models.CharField(max_length=30)),
                ('Mother_Surname', models.CharField(max_length=20)),
                ('Money_Left', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('User_Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
