# Generated by Django 5.1.2 on 2024-11-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_person_user_person_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
