# Generated by Django 5.1.2 on 2024-11-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
