# Generated by Django 5.1.2 on 2024-11-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_person_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
